### PR TITLE
Fix new-contract when use custom workspace dir (fixes #23)

### LINKED ISSUE #23: The new-contract command should alter Cargo.toml under `workspace_dir` instead of the project dir
In the current version, even we specific `workspace_dir`, the new-contract still add a rust contract to the `/Cargo.toml`.

### PR DESCRIPTION
**Pull request by TheWaWaR**

### CODE REVIEW

File: src/recipe/rust.rs [hunk 1]
```diff
@@ -73,11 +73,23 @@ impl Rust {
         // rewrite config
         {
             println!("Rewrite Cargo.toml");
-            let mut cargo_path = self.context.project_path.clone();
+            let mut cargo_path = self.context.workspace_dir()?;
+            let workspace_member = if let Some(Some(CONTRACTS_DIR)) = self
```
Comment (jjyr) [inline src/recipe/rust.rs]: Why do you using a constant style variable name?

File: src/project_context.rs [hunk 2]
```diff
@@ -91,15 +91,36 @@ impl Context {
...
+    pub fn workspace_dir(&self) -> Result<PathBuf> {
+        let mut path = self.project_path.clone();
+        if let Some(workspace_dir) = self.config.rust.workspace_dir.as_ref() {
+            match workspace_dir.to_str() {
+                Some(".") => {}
+                Some(CONTRACTS_DIR) => {
+                    path.push(workspace_dir);
+                }
+                dir => {
+                    return Err(anyhow!("Invalid `workspace_dir` config: {:?}, only allowed \".\" or \"contracts\".", dir));
```
Comment (jjyr) [inline src/project_context.rs:103]: Why? We have no reason to prevent us from accepting more paths.

https://doc.rust-lang.org/stable/std/path/struct.Path.html#method.canonicalize

**Review by jjyr — APPROVED** [review]
